### ISSUE TITLE
Document how to migrate from dev to prod

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/docs-gg-prod#18]
We need a documentation page that discusses the considerations around moving a configuration from dev to prod. For example, is there a way to export the configuration from Postgres?

**Comment by shmorri** [comment]
@ldeveloperl1985 , could you give me a rundown on this to add to the docs?

**Comment by ldeveloperl1985** [comment]
@shmorri just added in configuration section
https://github.com/GluuFederation/docs-gg-prod/blob/4.0.beta/docs/source/configuration.md#migrate-from-development-to-production-server
@nynymike please take a look on this section

**Comment by willow9886** [comment]
https://gluu.org/docs/gg/configuration/#migrate-from-dev-to-prod
