### ISSUE TITLE
Reduce duplicated content in GG docs

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/docs-gg-prod#20]
There is information duplicated in the plugin section and elsewhere in the GG docs. We should centralize this content into one location.

For example, the table with URL pattern matching syntax.

**Comment by ldeveloperl1985** [comment]
Done in https://github.com/GluuFederation/docs-gg-prod/commit/98cbce5be053f478c2629a479dc67455ec1d28ce
@shmorri  please check and confirm
